
name: Main workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        node_version: [12.x]
        python_version: [3.8.x]

    runs-on: ubuntu-latest

    steps:

    - name: Branch Name
      run: echo Running on branch ${GITHUB_REF##*/}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_}:${GITHUB_REF##*/} }
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_:${GITHUB_REF##*/}:${GITHUB_REF##*/}  }}
        aws-region: us-east-1

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install NPM Packages
      run: |
        npm install i -g serverless
        npm install

    - name: Serverless Deploy
      run: |
        if [[ $GITHUB_REF##*/ = "master" ]]; then
          serverless deploy --stage dev --verbose --conceal

        elif [[ $GITHUB_REF##*/ = "staging" ]]; then
          serverless deploy --stage dev2 --verbose --conceal
        fi


