
name: Main workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        node_version: [12.x]
        python_version: [3.8.x]

    runs-on: ubuntu-latest

    steps:

    - name: Branch Name
      run: echo Branch $GITHUB_HEAD_REF #${GITHUB_REF##*/}
        
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install Python Requirements
      run: ./scripts/installDeps.sh

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install NPM Packages
      run: |
        npm install i -g serverless
        npm install

    - name: Serverless Deploy
      run: |
            if [[ $GITHUB_HEAD_REF = "master" ]]; then
              serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID_PRODUCTION --secret $AWS_SECRET_ACCESS_KEY_PRODUCTION --stage prod
              ./scripts/deploy.sh prod
            elif [[ $GITHUB_HEAD_REF = "staging" ]]; then
              serverless config credentials --provider aws --key $AWS_ACCESS_KEY_ID_STAGING --secret $AWS_SECRET_ACCESS_KEY_STAGING --stage dev
              ./scripts/deploy.sh dev
            fi

            serverless deploy --stage test --verbose --conceal
