
name: Tests

on:
  pull_request:
    branches: 
      - master
      - staging

jobs:
  build:

    strategy:
      matrix:
        node_version: [12.x]
        python_version: [3.8.x]

    runs-on: ubuntu-latest

    steps:

    - name: Install AWS CLI
      run: |
        curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
        unzip awscli-bundle.zip
        sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws

    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: Install NPM Packages
      run: npm install -g aws-cdk

    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python_version }}
    
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m venv .env
        source .env/bin/activate
        pip3 install -r requirements.txt
    
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     # stop the build if there are Python syntax errors or undefined names
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run Tests
      run: pytest
